### ISSUE TITLE
Line 151 - Model is not defined.

### ISSUE THREAD

**Issue by lmiranda2** [evanhobbs/angular-backbone-models#1]
Hi,

First of all, I have to say that is a great project.

I was trying to use your library and I got an error on line 151 - model is not defined.

My workaround was to change model to that. Is that correct?

Luiz

**Comment by evanhobbs** [comment]
Hi Luiz,

Thanks - you're absolutely correct. Sorry for slow reply; I was on vacation... I just committed the fix to master...
